// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SafeNavigation.Infrastructure.Persistence;

#nullable disable

namespace SafeNavigation.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SafeNavigationDbContext))]
    [Migration("20260714200228_InitialBackendSchema")]
    partial class InitialBackendSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SafeNavigation.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alert_type");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<Guid>("GuardianId")
                        .HasColumnType("uuid")
                        .HasColumnName("guardian_id");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_entity_id");

                    b.Property<string>("RelatedEntityType")
                        .HasColumnType("text")
                        .HasColumnName("related_entity_type");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_alerts");

                    b.HasIndex("GuardianId", "Status", "CreatedAt")
                        .HasDatabaseName("ix_alerts_guardian_id_status_created_at");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("SafeNavigation.Domain.Entities.AppUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppName")
                        .HasColumnType("text")
                        .HasColumnName("app_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset?>("FirstUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_used_at");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<int>("OpenCountEstimate")
                        .HasColumnType("integer")
                        .HasColumnName("open_count_estimate");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("package_name");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<long>("TotalForegroundMs")
                        .HasColumnType("bigint")
                        .HasColumnName("total_foreground_ms");

                    b.Property<DateOnly>("UsageDate")
                        .HasColumnType("date")
                        .HasColumnName("usage_date");

                    b.HasKey("Id")
                        .HasName("pk_app_usage");

                    b.HasIndex("DeviceId", "UsageDate")
                        .HasDatabaseName("ix_app_usage_device_id_usage_date");

                    b.HasIndex("DeviceId", "PackageName", "UsageDate")
                        .IsUnique()
                        .HasDatabaseName("ix_app_usage_device_id_package_name_usage_date");

                    b.ToTable("app_usage", (string)null);
                });

            modelBuilder.Entity("SafeNavigation.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpHash")
                        .HasColumnType("text")
                        .HasColumnName("ip_hash");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_audit_logs_created_at");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("SafeNavigation.Domain.Entities.BlockAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attempted_at");

                    b.Property<Guid?>("BlockingRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("blocking_rule_id");

                    b.Property<string>("ChildRequestStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("child_request_status");

                    b.Property<string>("CorrelationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correlation_type");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("Domain")
                        .HasColumnType("text")
                        .HasColumnName("domain");

                    b.Property<string>("ForegroundPackageName")
                        .HasColumnType("text")
                        .HasColumnName("foreground_package_name");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<int?>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("protocol");

                    b.HasKey("Id")
                        .HasName("pk_block_attempts");

                    b.HasIndex("DeviceId", "AttemptedAt")
                        .HasDatabaseName("ix_block_attempts_device_id_attempted_at");

                    b.ToTable("block_attempts", (string)null);
                });

            modelBuilder.Entity("SafeNavigation.Domain.Entities.BlockingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<Guid?>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<Guid>("GuardianId")
                        .HasColumnType("uuid")
                        .HasColumnName("guardian_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rule_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_blocking_rules");

                    b.HasIndex("GuardianId")
                        .HasDatabaseName("ix_blocking_rules_guardian_id");

                    b.HasIndex("ChildId", "Enabled")
                        .HasDatabaseName("ix_blocking_rules_child_id_enabled");

                    b.HasIndex("DeviceId", "Enabled")
                        .HasDatabaseName("ix_blocking_rules_device_id_enabled");

                    b.ToTable("blocking_rules", (string)null);
                });

            modelBuilder.Entity("SafeNavigation.Domain.Entities.Child", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("integer")
                        .HasColumnName("birth_year");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<Guid>("GuardianId")
                        .HasColumnType("uuid")
                        .HasColumnName("guardian_id");

                    b.HasKey("Id")
                        .HasName("pk_children");

                    b.HasIndex("GuardianId")
                        .HasDatabaseName("ix_children_guardian_id");

                    b.ToTable("children", (string)null);
                });

            modelBuilder.Entity("SafeNavigation.Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AndroidVersion")
                        .HasColumnType("text")
                        .HasColumnName("android_version");

                    b.Property<string>("AppVersion")
                        .HasColumnType("text")
                        .HasColumnName("app_version");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DevicePublicId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_public_id");

                    b.Property<DateTimeOffset?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_at");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("text")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Model")
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("platform");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasIndex("ChildId")
                        .HasDatabaseName("ix_devices_child_id");

                    b.HasIndex("DevicePublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_devices_device_public_id");

                    b.HasIndex("LastSyncAt")
                        .HasDatabaseName("ix_devices_last_sync_at");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("SafeNavigation.Domain.Entities.DeviceConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ConfigVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("config_version");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<int>("RetentionDays")
                        .HasColumnType("integer")
                        .HasColumnName("retention_days");

                    b.Property<int>("SyncIntervalMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("sync_interval_minutes");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("UsageStatsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("usage_stats_enabled");

                    b.Property<bool>("VpnEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("vpn_enabled");

                    b.HasKey("Id")
                        .HasName("pk_device_configs");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasDatabaseName("ix_device_configs_device_id");

                    b.ToTable("device_configs", (string)null);
                });

            modelBuilder.Entity("SafeNavigation.Domain.Entities.DeviceRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_device_refresh_tokens");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_device_refresh_tokens_device_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_device_refresh_tokens_token_hash");

                    b.ToTable("device_refresh_tokens", (string)null);
                });

            modelBuilder.Entity("SafeNavigation.Domain.Entities.DomainAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_count");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("CorrelationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correlation_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("Domain")
                        .HasColumnType("text")
                        .HasColumnName("domain");

                    b.Property<DateTimeOffset>("FirstAccessAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_access_at");

                    b.Property<string>("ForegroundPackageName")
                        .HasColumnType("text")
                        .HasColumnName("foreground_package_name");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("LastAccessAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_access_at");

                    b.Property<int?>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("protocol");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_domain_accesses");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_domain_accesses_category_id");

                    b.HasIndex("DeviceId", "Domain", "LastAccessAt")
                        .HasDatabaseName("ix_domain_accesses_device_id_domain_last_access_at");

                    b.HasIndex("DeviceId", "IpAddress", "LastAccessAt")
                        .HasDatabaseName("ix_domain_accesses_device_id_ip_address_last_access_at");

                    b.ToTable("domain_accesses", (string)null);
                });

            modelBuilder.Entity("SafeNavigation.Domain.Entities.DomainCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("integer")
                        .HasColumnName("risk_level");

                    b.HasKey("Id")
                        .HasName("pk_domain_categories");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_domain_categories_name");

                    b.ToTable("domain_categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000001"),
                            DisplayName = "Redes sociais",
                            Name = "social",
                            RiskLevel = 1
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000002"),
                            DisplayName = "Videos",
                            Name = "video",
                            RiskLevel = 1
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000003"),
                            DisplayName = "Jogos",
                            Name = "games",
                            RiskLevel = 1
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000004"),
                            DisplayName = "Educacao",
                            Name = "education",
                            RiskLevel = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000005"),
                            DisplayName = "Noticias",
                            Name = "news",
                            RiskLevel = 1
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000006"),
                            DisplayName = "Conteudo adulto",
                            Name = "adult",
                            RiskLevel = 5
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000007"),
                            DisplayName = "Apostas",
                            Name = "gambling",
                            RiskLevel = 5
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000008"),
                            DisplayName = "Sites desconhecidos",
                            Name = "unknown",
                            RiskLevel = 2
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000009"),
                            DisplayName = "Malicioso",
                            Name = "malicious",
                            RiskLevel = 5
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000010"),
                            DisplayName = "Violencia explicita",
                            Name = "violence",
                            RiskLevel = 5
                        });
                });

            modelBuilder.Entity("SafeNavigation.Domain.Entities.Guardian", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_guardians");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_guardians_email");

                    b.ToTable("guardians", (string)null);
                });

            modelBuilder.Entity("SafeNavigation.Domain.Entities.PairingCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChildDisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("child_display_name");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceName")
                        .HasColumnType("text")
                        .HasColumnName("device_name");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("GuardianId")
                        .HasColumnType("uuid")
                        .HasColumnName("guardian_id");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("Id")
                        .HasName("pk_pairing_codes");

                    b.HasIndex("CodeHash")
                        .IsUnique()
                        .HasDatabaseName("ix_pairing_codes_code_hash");

                    b.HasIndex("GuardianId", "ExpiresAt")
                        .HasDatabaseName("ix_pairing_codes_guardian_id_expires_at");

                    b.ToTable("pairing_codes", (string)null);
                });

            modelBuilder.Entity("SafeNavigation.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("GuardianId")
                        .HasColumnType("uuid")
                        .HasColumnName("guardian_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("GuardianId")
                        .HasDatabaseName("ix_refresh_tokens_guardian_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("SafeNavigation.Domain.Entities.SyncBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_batch_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("ErrorSummary")
                        .HasColumnType("text")
                        .HasColumnName("error_summary");

                    b.Property<int>("RecordsAccepted")
                        .HasColumnType("integer")
                        .HasColumnName("records_accepted");

                    b.Property<int>("RecordsReceived")
                        .HasColumnType("integer")
                        .HasColumnName("records_received");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_sync_batches");

                    b.HasIndex("DeviceId", "ClientBatchId")
                        .IsUnique()
                        .HasDatabaseName("ix_sync_batches_device_id_client_batch_id");

                    b.ToTable("sync_batches", (string)null);
                });

            modelBuilder.Entity("SafeNavigation.Domain.Entities.AppUsage", b =>
                {
                    b.HasOne("SafeNavigation.Domain.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_app_usage_devices_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("SafeNavigation.Domain.Entities.BlockAttempt", b =>
                {
                    b.HasOne("SafeNavigation.Domain.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_block_attempts_devices_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("SafeNavigation.Domain.Entities.Child", b =>
                {
                    b.HasOne("SafeNavigation.Domain.Entities.Guardian", "Guardian")
                        .WithMany("Children")
                        .HasForeignKey("GuardianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_children_guardians_guardian_id");

                    b.Navigation("Guardian");
                });

            modelBuilder.Entity("SafeNavigation.Domain.Entities.Device", b =>
                {
                    b.HasOne("SafeNavigation.Domain.Entities.Child", "Child")
                        .WithMany("Devices")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_devices_children_child_id");

                    b.Navigation("Child");
                });

            modelBuilder.Entity("SafeNavigation.Domain.Entities.DeviceConfig", b =>
                {
                    b.HasOne("SafeNavigation.Domain.Entities.Device", "Device")
                        .WithOne("Config")
                        .HasForeignKey("SafeNavigation.Domain.Entities.DeviceConfig", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_configs_devices_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("SafeNavigation.Domain.Entities.DeviceRefreshToken", b =>
                {
                    b.HasOne("SafeNavigation.Domain.Entities.Device", "Device")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_refresh_tokens_devices_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("SafeNavigation.Domain.Entities.DomainAccess", b =>
                {
                    b.HasOne("SafeNavigation.Domain.Entities.DomainCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("fk_domain_accesses_domain_categories_category_id");

                    b.HasOne("SafeNavigation.Domain.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_domain_accesses_devices_device_id");

                    b.Navigation("Category");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("SafeNavigation.Domain.Entities.PairingCode", b =>
                {
                    b.HasOne("SafeNavigation.Domain.Entities.Guardian", "Guardian")
                        .WithMany()
                        .HasForeignKey("GuardianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pairing_codes_guardians_guardian_id");

                    b.Navigation("Guardian");
                });

            modelBuilder.Entity("SafeNavigation.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("SafeNavigation.Domain.Entities.Guardian", "Guardian")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("GuardianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_guardians_guardian_id");

                    b.Navigation("Guardian");
                });

            modelBuilder.Entity("SafeNavigation.Domain.Entities.SyncBatch", b =>
                {
                    b.HasOne("SafeNavigation.Domain.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sync_batches_devices_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("SafeNavigation.Domain.Entities.Child", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("SafeNavigation.Domain.Entities.Device", b =>
                {
                    b.Navigation("Config");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("SafeNavigation.Domain.Entities.Guardian", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
